name: 🐳 Deploy App - Kubernetes Dev

on:
  push:
    branches: ["main"]

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: neryolo
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: neryolo/az_app:latest

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: neryolo/az_app:${{ github.sha }}